services:
  sistema-emprestimo:
    build:
      context: ./sistema-emprestimo
      dockerfile: ../Dockerfile
    container_name: sistema-emprestimo
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aed
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy

  sistema-margem:
    build:
      context: ./sistema-margem
      dockerfile: ../Dockerfile
    container_name: sistema-margem
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aed
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy

  sistema-analise:
    build:
      context: ./sistema-analise
      dockerfile: ../Dockerfile
    container_name: sistema-analise
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aed
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
