CREATE TABLE IF NOT EXISTS evento_processado (
    evento_id     VARCHAR(64) PRIMARY KEY,
    processado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS margem (
    id UUID PRIMARY KEY,
    cpf VARCHAR(11) NOT NULL,
    valor DECIMAL(10, 2) NOT NULL,
    codigo_verba INT NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    tipo VARCHAR(20) NOT NULL
);
